### ISSUE TITLE
all the dice are non

### ISSUE THREAD

**Issue by Ching-Nam** [hsiangyuzhao/PANet#4]
Hello, dear author. Thanks for replying to my last quetion. I tried different ways to run the code after that. Firstly, I rewrite the code like this "dice_et = dice_metric(y_pred=predictions[:, 1:2, ...], y=ground_truth[:, 1:2, ...]),  dice_et, dice_et_not_nans = do_metric_reduction(dice_et, reduction = MetricReduction.None)".  However all the dice and hd are non. Then I change the version of monai to 0.5, which can return two values. But all the dice and hd are still non. Can you help me fix this problem or tell me the version of monai you used? Thank you very much!

**Comment by hsiangyuzhao** [comment]
> dice_et = dice_metric(y_pred=predictions[:, 1:2, ...], y=ground_truth[:, 1:2, ...]), dice_et, dice_et_not_nans = do_metric_reduction(dice_et, reduction = MetricReduction.None)

could you provide the definition of the function "do_metric_reduction"? If you turn on the "get_not_nans" flag in "dice_metric", it should be fine, no further modification needed.

**Comment by Ching-Nam** [comment]
Thank you very much. I think it is okay now.
