### ISSUE TITLE
Why is there no PANET ？

### ISSUE THREAD

**Issue by Sunmengqian** [hsiangyuzhao/PANet#6]
python train.py --model panet --patch_test --ds

Traceback (most recent call last):
  File "train.py", line 376, in <module>
    main()
  File "train.py", line 67, in main
    assert model_name in ('unet', 'fuse', 'attention', 'enhanced', 'cascade'), 'Model name is wrong!'
AssertionError: Model name is wrong

**Comment by hsiangyuzhao** [comment]
The bug has been fixed. Thanks for the issue.

**Comment by Eight3H** [comment]
> The bug has been fixed. Thanks for the issue.

hello,In the past few days, there has been a problem with the verification on the official website of 20, and my submission shows that it has been pending
